### ISSUE TITLE
How to support conditional compilation with/without CAPNG_AMBIENT & CAPNG_SELECT_ALL?

### ISSUE THREAD

**Issue by snarkmaster** [stevegrubb/libcap-ng#20]
At the moment, these are `enum`s instead of preprocessor symbols, so I cannot just do this:

```
#ifdef CAPNG_SELECT_ALL
    capng_clear(CAPNG_SELECT_ALL); 
#else
    capng_clear(CAPNG_SELECT_BOTH); 
#endif
```

Would you prefer to convert these to macros, or to provide a `#define CAPNG_SUPPORTS_AMBIENT 1` in `0.8.1`?

**Comment by stevegrubb** [comment]
I added AC_CHECK_DECLS([CAPNG_AMBIENT], [], [], [[#include <cap-ng.h>]])  to cap-ng.m4. Assuming your project uses the m4 dropin, it will put something in your config.h.

**Comment by snarkmaster** [comment]
Unfortunately, my project does not, and will likely never use autotools. The `.c` file will most likely be built by Buck (that's the native build system for the project), or possibly CMake. AFAIK, neither speaks autoconf m4.

I think I can get by with doing the conditional compilation `#define`s manually on my build end, though. It's just mildly annoying :)

**Comment by snarkmaster** [comment]
I'm leaving this open in case (a) you decide it's OK add a feature tag to your `.h` (easier to use for sure, since it's independent of the build system). If you prefer (b) to delegate it to the build setup of the user, which also works, but scales as O(number of build systems), feel free to close this out.

**Comment by stevegrubb** [comment]
commit 1397f99 should fix this. It adds #define CAPNG_SUPPORTS_AMBIENT.
