### ISSUE TITLE
Upgrade to libcap-ng 0.8.1 breaks GNOME Keyring and other projects

### ISSUE THREAD

**Issue by diabonas** [stevegrubb/libcap-ng#21]
After upgrading libcap-ng to the freshly released version 0.8.1, attempting to start [GNOME Keyring](https://wiki.gnome.org/Projects/GnomeKeyring) fails with an error message:
```
$ gnome-keyring-daemon --start
gnome-keyring-daemon: error dropping process capabilities, aborting
```
I have bisected this to commit 6a24a9c5e2f3af1d56430417ee8c9a04ead38e6c ("capng_apply error update"), so apparently GNOME Keyring does not expect `capng_apply` to fail in this situation. The relevant capability handling code in GNOME Keyring looks [as follows](https://gitlab.gnome.org/GNOME/gnome-keyring/-/blob/4f531000ae49d89f800e00572271ad3d704a1a01/daemon/gkd-capability.c#L94):
```C
capng_clear (CAPNG_SELECT_BOTH);
if (capng_update (CAPNG_ADD,
                  CAPNG_EFFECTIVE|CAPNG_PERMITTED,
                  CAP_IPC_LOCK) != 0)
	early_error ("error dropping process capabilities");
if (capng_apply (CAPNG_SELECT_BOTH) != 0)
	early_error ("error dropping process capabilities");
```

Downstream Arch Linux bug report: [FS#68664](https://bugs.archlinux.org/task/68664)

**Comment by diabonas** [comment]
IIUC this code fails because `gnome-keyring-daemon` does not have `CAP_SETPCAP` and tries to change its capability bounding set anyway, so [`capng_apply` returns `-4`](https://github.com/stevegrubb/libcap-ng/blob/2ab6a03b78cfa7620641c772d13ddbf3b405576b/docs/capng_apply.3#L24). I guess this behaviour is technically correct, but probably comes as a surprise for many developers, especially since this code is modelled exactly after example 2) in the [libcap-ng README](https://github.com/stevegrubb/libcap-ng#c-examples). Is there a better way of doing this without adding `CAP_SETPCAP` or giving up error checking?

**Comment by diabonas** [comment]
In any case I don't think this should [fail early](https://github.com/stevegrubb/libcap-ng/blob/7d231cf93a8067468c4cee7dad44dee1798851f3/src/cap-ng.c#L707) before even [attempting to set the normal `CAPNG_SELECT_CAPS`](https://github.com/stevegrubb/libcap-ng/blob/7d231cf93a8067468c4cee7dad44dee1798851f3/src/cap-ng.c#L711-L717): right now, probably a lot of legacy code just completely and silently fails trying to set capabilities because it uses the example code from the documentation without checking the return value of `capng_apply`.

**Comment by diabonas** [comment]
[LinuxCIFS utils](https://wiki.samba.org/index.php/LinuxCIFS_utils) is affected by this change [as well](https://github.com/Distrotech/cifs-utils/blob/0b0b81a533a8990d9a19e80b317a320c1d8a09d3/mount.cifs.c#L340-L343):
```C
if (capng_apply(CAPNG_SELECT_BOTH)) {
	fprintf(stderr, "Unable to apply new capability set.\n");
	return EX_SYSERR;
}
```
Downstream Arch Linux bug report: [FS#68666](https://bugs.archlinux.org/task/68666)

**Comment by diabonas** [comment]
> In any case I don't think this should [fail early](https://github.com/stevegrubb/libcap-ng/blob/7d231cf93a8067468c4cee7dad44dee1798851f3/src/cap-ng.c#L707) before even [attempting to set the normal `CAPNG_SELECT_CAPS`](https://github.com/stevegrubb/libcap-ng/blob/7d231cf93a8067468c4cee7dad44dee1798851f3/src/cap-ng.c#L711-L717): right now, probably a lot of legacy code just completely and silently fails trying to set capabilities because it uses the example code from the documentation without checking the return value of `capng_apply`.

To fix this part of the issue, I have opened #23. Hopefully this strikes a balance between the need for better error checking and not breaking legacy code: projects that perform error checking on `capng_apply` will need to be updated for the new libcap-ng release, while code not doing any error checking will continue working as before instead of completely failing to apply the capabilities.

In the [downstream bug report](https://bugs.archlinux.org/task/68664#comment194286), @dvzrv provided a link to a [fix for GNOME keyring](https://gitlab.gnome.org/GNOME/gnome-keyring/-/merge_requests/33) by libcap-ng mainainer @stevegrubb. I noticed that this fix [doesn't even apply `CAPNG_SELECT_CAPS` any more](https://gitlab.gnome.org/GNOME/gnome-keyring/-/merge_requests/33#note_965430) if `CAP_SETPCAP` is not given, which previous versions of GNOME keyring and libcap-ng used to do. Could you comment on whether that is the intended behaviour, please?

For other projects like LinuxCIFS utils, no such fixes [appear to be available yet](https://bugs.archlinux.org/task/68666#comment194287).

**Comment by AdamWill** [comment]
Confirming both issues hit me on Rawhide today after an upgrade.

**Comment by SoapGentoo** [comment]
I can confirm this for Gentoo too

**Comment by stevegrubb** [comment]
I have placed a merge request here:
https://gitlab.gnome.org/GNOME/gnome-keyring/-/merge_requests/34

**Comment by stevegrubb** [comment]
Commit fda0224 should help the situation. Will probably push a new release early next week.

**Comment by stevegrubb** [comment]
**Message to package maintainers:** Fedora has added commit fda0224 and applied this patch on top which blocks the bad return codes: https://src.fedoraproject.org/rpms/libcap-ng/blob/master/f/libcap-ng-0.8.2-apply-disable.patch
Assuming this calms down issues, this provides a place to hook for syslog'ing apps that are not using capabilities correctly so that we can fix them. I don't expect, as of now, to carry the syslog patch in libcap-ng. But rather point to it as a downstream add-on that distros can use in their experimental branch to work out problems.

**Comment by diabonas** [comment]
> [LinuxCIFS utils](https://wiki.samba.org/index.php/LinuxCIFS_utils) is affected by this change [as well](https://git.samba.org/?p=cifs-utils.git;a=blob;f=mount.cifs.c;h=4feb397a1439ca3e19491d4d77b9c09f7f90fce1;hb=HEAD#l358)

I sent the following patches upstream to the [linux-cifs mailing list](https://marc.info/?l=linux-cifs&m=160595758021262):
```patch
From f4e7c84467152624a288351321c8664dbf3364af Mon Sep 17 00:00:00 2001
From: Jonas Witschel <diabonas@archlinux.org>
Date: Sat, 21 Nov 2020 11:41:26 +0100
Subject: [PATCH 1/2] mount.cifs: update the cap bounding set only when
 CAP_SETPCAP is given

libcap-ng 0.8.1 tightened the error checking on capng_apply, returning an error
of -4 when trying to update the capability bounding set without having the
CAP_SETPCAP capability to be able to do so. Previous versions of libcap-ng
silently skipped updating the bounding set and only updated the normal
CAPNG_SELECT_CAPS capabilities instead.

Check beforehand whether we have CAP_SETPCAP, in which case we can use
CAPNG_SELECT_BOTH to update both the normal capabilities and the bounding set.
Otherwise, we can at least update the normal capabilities, but refrain from
trying to update the bounding set to avoid getting an error.

Signed-off-by: Jonas Witschel <diabonas@archlinux.org>
---
 mount.cifs.c | 7 ++++++-
 1 file changed, 6 insertions(+), 1 deletion(-)

diff --git a/mount.cifs.c b/mount.cifs.c
index 4feb397..88b8b69 100644
--- a/mount.cifs.c
+++ b/mount.cifs.c
@@ -338,6 +338,8 @@ static int set_password(struct parsed_mount_info *parsed_info, const char *src)
 static int
 drop_capabilities(int parent)
 {
+	capng_select_t set = CAPNG_SELECT_CAPS;
+
 	capng_setpid(getpid());
 	capng_clear(CAPNG_SELECT_BOTH);
 	if (parent) {
@@ -355,7 +357,10 @@ drop_capabilities(int parent)
 			return EX_SYSERR;
 		}
 	}
-	if (capng_apply(CAPNG_SELECT_BOTH)) {
+	if (capng_have_capability(CAPNG_EFFECTIVE, CAP_SETPCAP)) {
+		set = CAPNG_SELECT_BOTH;
+	}
+	if (capng_apply(set)) {
 		fprintf(stderr, "Unable to apply new capability set.\n");
 		return EX_SYSERR;
 	}
--
2.29.2


From 64dfbafe7a0639a96d67f0b840b6e6498e1f68a9 Mon Sep 17 00:00:00 2001
From: Jonas Witschel <diabonas@archlinux.org>
Date: Sat, 21 Nov 2020 11:48:33 +0100
Subject: [PATCH 2/2] cifs.upall: update the cap bounding set only when
 CAP_SETPCAP is given

libcap-ng 0.8.1 tightened the error checking on capng_apply, returning an error
of -4 when trying to update the capability bounding set without having the
CAP_SETPCAP capability to be able to do so. Previous versions of libcap-ng
silently skipped updating the bounding set and only updated the normal
CAPNG_SELECT_CAPS capabilities instead.

Check beforehand whether we have CAP_SETPCAP, in which case we can use
CAPNG_SELECT_BOTH to update both the normal capabilities and the bounding set.
Otherwise, we can at least update the normal capabilities, but refrain from
trying to update the bounding set to avoid getting an error.

Signed-off-by: Jonas Witschel <diabonas@archlinux.org>
---
 cifs.upcall.c | 7 ++++++-
 1 file changed, 6 insertions(+), 1 deletion(-)

diff --git a/cifs.upcall.c b/cifs.upcall.c
index 1559434..af1a0b0 100644
--- a/cifs.upcall.c
+++ b/cifs.upcall.c
@@ -88,6 +88,8 @@ typedef enum _sectype {
 static int
 trim_capabilities(bool need_environ)
 {
+	capng_select_t set = CAPNG_SELECT_CAPS;
+
 	capng_clear(CAPNG_SELECT_BOTH);

 	/* SETUID and SETGID to change uid, gid, and grouplist */
@@ -105,7 +107,10 @@ trim_capabilities(bool need_environ)
 		return 1;
 	}

-	if (capng_apply(CAPNG_SELECT_BOTH)) {
+	if (capng_have_capability(CAPNG_EFFECTIVE, CAP_SETPCAP)) {
+		set = CAPNG_SELECT_BOTH;
+	}
+	if (capng_apply(set)) {
 		syslog(LOG_ERR, "%s: Unable to apply capability set: %m\n", __func__);
 		return 1;
 	}
--
2.29.2
```

**Comment by diabonas** [comment]
Other projects I could find that might potentially be affected by this change because they perform error checking on `capng_apply(CAPNG_SELECT_BOTH)` without checking for `CAP_SETPCAP` first are:

- [Ceph](https://github.com/ceph/ceph/blob/d472ab97534090447fd1f4d50bedd323ca80d696/src/mount/mount.ceph.c#L115-L118)
- [QEMU](https://github.com/qemu/qemu/blob/834b9273d5cdab68180dc8c84d641aaa4344b057/fsdev/virtfs-proxy-helper.c#L104-L107)

Most other projects I looked at don't do any error checking on `capng_apply`, so they should be fine with the upcoming release including commit https://github.com/stevegrubb/libcap-ng/commit/fda0224fea4f01b77bd07ac195b3baaaf1a28fca.

**Comment by stevegrubb** [comment]
Patch above looks good. Thanks for sending it to their mail list!  I also have reports openconnect may be affected.

**Comment by diabonas** [comment]
> Commit [fda0224](https://github.com/stevegrubb/libcap-ng/commit/fda0224fea4f01b77bd07ac195b3baaaf1a28fca) should help the situation. Will probably push a new release early next week.

A new libcap-ng including this commit would be much appreciated :)

**Comment by stevegrubb** [comment]
A new release is available. I suppose this issue can be closed.

**Comment by diabonas** [comment]
Thank you very much for cutting the new release! I agree that this issue can be closed, since all other potentially necessary fixes need to be made downstream. Incidentally, the patches for LinuxCIFS utils have just been [merged](https://marc.info/?l=linux-cifs&m=160754144911560): https://github.com/piastry/cifs-utils/commit/f1ab2261ad44b866751ed556020eac417575e2aa, https://github.com/piastry/cifs-utils/commit/cc70f134ebaa3eef854454fc719aaaabac611494
