### ISSUE TITLE
Improve last cap detection

### ISSUE THREAD

**Issue by ericonr** [stevegrubb/libcap-ng#22]
Hi! I'm developing some changes in util-linux ( https://github.com/karelzak/util-linux/pull/1187 ) for how they detect the last cap from the kernel, and I would like to know if you'd accept a PR to add the same changes here.

Also, do you think a `capng_get_last_cap` call could be added to the API?

**Comment by stevegrubb** [comment]
Sure. Looks like I might be doing another release soon.

**Comment by stevegrubb** [comment]
Hi, were you going to submit a pull request?

**Comment by ericonr** [comment]
I will! If you want to go ahead and implement it / make a release without it, it's ok for me.

Otherwise I will try to get you a patch as soon as possible, probably until the weekend.

**Comment by stevegrubb** [comment]
I  am holding the next release pending this pull request. After looking at the current code (back when you mentioned it), yeah. It can be improved. And I'd like to include that in the next round.
