### ISSUE TITLE
libdrop_ambient breaks compile if PR_CAP_AMBIENT is undefined

### ISSUE THREAD

**Issue by SJLC** [stevegrubb/libcap-ng#24]
In cap-ng.c all uses of PR_CAP_AMBIENT are protected by `#ifdef PR_CAP_AMBIENT` but libdrop_ambient.c does not have the check. Of course libdrop_ambient is useless on platforms that don't have ambient capability support, but I propose just adding the ifdef there instead of trying to tinker the autotools files to skip building the library altogether when the support is missing (which shoould be pretty rare case by now).

What do you think? Would you accept a pull request for something like this?

```
--- a/src/libdrop_ambient.c     2020-11-18 10:39:31.000000000 -0800
+++ b/src/libdrop_ambient.c     2020-12-02 15:59:10.977235659 -0800
@@ -25,6 +25,8 @@
 
 void __attribute__ ((constructor)) init(void)
 {
+#ifdef PR_CAP_AMBIENT
        prctl(PR_CAP_AMBIENT, PR_CAP_AMBIENT_CLEAR_ALL, 0, 0, 0);
+#endif
 }

```

**Comment by stevegrubb** [comment]
Well, if PR_CAP_AMBIENT is not defined, there is no point in libdrop_ambient.so. So, this should be at a higher level where it's not even compiled. I would accept a configure.ac/Makefile.am patch for this. If this is not something you like to delve into, then I can gen one up. But I'd like to offer you the chance to contribute if you so wish

**Comment by SJLC** [comment]
Thanks for being willing to fix something rare. I have done autotools before, so will look into a fix at the configure level today.

**Comment by SJLC** [comment]
I tested the proposed commit on both build host and legacy target; the library in question builds / is skipped respectively.

**Comment by stevegrubb** [comment]
closing this since fix is merged. Thanks!
