### ISSUE TITLE
Use uid_t and gid_t in capng_change_id

### ISSUE THREAD

**Issue by ghost** [stevegrubb/libcap-ng#3]
arguments "uid" and "gid" of capng_change_id should be changed to uid_t and gid_t.
should i submit a pull request?

**Comment by stevegrubb** [comment]
Actually, the man page needs updating to explain what effect passing -1 for uid or gid does. :-)

**Comment by janikrabe** [comment]
I can work on updating the man page; however, I also think it would be good for the arguments to be changed to `uid_t` and `gid_t` in this function. If I'm not mistaken, `(uid_t) -1` and `(gid_t) -1` are reserved by POSIX for the same purpose. For example, [chown](http://pubs.opengroup.org/onlinepubs/009695399/functions/chown.html) does something similar.

**Comment by stevegrubb** [comment]
Yes. The reason is that they can legally be -1 which means do not change the uid or gid, leave it "as is". This is missing on the man page.

**Comment by stevegrubb** [comment]
I updated the man page to explain the usage of -1 for uid and gid. Hope that clears up any confusion. Thanks for raising this issue. It resulted in better documentation.

**Comment by janikrabe** [comment]
Thanks for the update!

Couldn't `(uid_t) -1` and `(gid_t) -1` be used to indicate that UID and GID should remain unchanged? That's precisely what [chown](http://pubs.opengroup.org/onlinepubs/009695399/functions/chown.html) does:

> If owner or group is specified as `(uid_t) -1` or `(gid_t) -1`, respectively, the corresponding ID … shall not be changed.

Apologies if I'm misunderstanding something here.

**Comment by stevegrubb** [comment]
Closing out this old issue. Man page update is best fix. Thanks for reporting the issue.
