### ISSUE TITLE
Tarball distribution issues.

### ISSUE THREAD

**Issue by mirschkyn** [stevegrubb/libcap-ng#34]
This is mostly for build environments and automated handling / downloading.

people.redhat.com is currently having issues. Redhat internal tracking ID: INC2158974
https://www.ssllabs.com/ssltest/analyze.html?d=people.redhat.com
The certificate chain is incomplete, leading to download issues if the certificate chain isn't ignored.

I was thinking of moving the libcap-ng download URL to github, but the github tarballs don't hash the same as the release tarballs.
I suspect these ones distributed here are just source balls, not "make dist" ones.

Either way, it currently causes a bit of a headache.
If it's an option, could you please distribute the proper release tarballs on github and make it a permanent hosting place?

**Comment by rossburton** [comment]
The automatic “source code” links are generated on demand and won’t be reliable over time either. The best practise is to generate a make dist like usual and upload it to the tag.

**Comment by mirschkyn** [comment]
people.redhat.com has been fixed.
I'll leave this issue open.
I think it's still a valuable thing to host the release tarballs here aswell.

**Comment by stevegrubb** [comment]
Thanks for reporting this. I opened a ticket and got the situation fixed. I've used people.redhat.com to distribute the audit package for over 15 years and never had a problem - except this one. I plan to continue distributing the sources as it has been. This was just a momentary glitch. Thank you for your patience.
