### ISSUE TITLE
Problem with namespaces

### ISSUE THREAD

**Issue by Amank001** [stevegrubb/libcap-ng#38]
libcap-ng seems to have some problem with namespaces. I am working with a container infrastructure like docker and i have written code to drop capabilites inside the container. It doesn't work when i enable both namespaces and resources. But it works when i do resource-only.

**Comment by stevegrubb** [comment]
Which namespaces are involved?

**Comment by fakeUser69** [comment]
Hi Steve,
Every namespace is involved. I suspected user ns might be the reason for
the problem but it wasn't. I disabled it and checked that it still didn't
work.

Thanks,
Aman

**Comment by stevegrubb** [comment]
The capabilities(7) man page has some mention about namespaces and capability interaction. If the process is under a different uid, you may need to grant capabilities and then change to the uid. If you had a minimal reproducer, I could look into it.

**Comment by Amank001** [comment]
capng_get_caps_process () returns -1 when namespaces are enabled. any idea why it fails ?

**Comment by stevegrubb** [comment]
It could fail for several reasons. An strace would be helpful in pinpointing why.
