### ISSUE TITLE
Build of libcap-ng failed with SWIG 4.2.0

### ISSUE THREAD

**Issue by jplesnik** [stevegrubb/libcap-ng#48]
I am testing rebuild of SWIG dependencies against version 4.2.0 in Fedora rawhide/40.

The build of `libcap-ng-0.8.4` is failing with this version.
```
swig -o capng_wrap.c -python -I. -I../.. -I/usr/include/python3.12 -I/usr/include/python3.12 ./../src/capng_swig.i
make[4]: Leaving directory '/builddir/build/BUILD/libcap-ng-0.8.4/bindings/python3'
./../src/capng_swig.i:33: Error: Unknown directive '%except'.
make[4]: *** [Makefile:878: capng_wrap.c] Error 1
make[3]: *** [Makefile:595: all-recursive] Error 1
make[2]: *** [Makefile:390: all-recursive] Error 1
make[1]: *** [Makefile:441: all-recursive] Error 1
make: *** [Makefile:373: all] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.98V4Nl (%build)
```

The reason is that features deprecated in SWIG 1.x and 2.x was removed. Instead ` %except` should be replaced by using `%exception`.

**Comment by taladar** [comment]
Same issue in Gentoo unstable with the same versions of libcap-ng and swig. I have not really found the correct %exception based replacement syntax though.

@jplesnik What did you use to replace that block?

**Comment by stevegrubb** [comment]
This code was copied over from the audit project. The audit project was modified 5 months ago to pin point the exception to audit_open. Libcap-ng doesn't quite have a function like that. I suppose the except code can be deleted and let exceptions be thrown in the python code. I don't have a good sense of how many projects that might affect. Python is not normally used for daemons or setuid programs. So, maybe there's no risk in deleting the exception handler?

**Comment by lucabonnix** [comment]
If you want to keep the exception handler, you can simply change "%except(python)" with "%exception" and add a dedicated exception for void functions (otherwise "result" variable is not defined):
```
--- libcap-ng-0.8.4.old/bindings/src/capng_swig.i       2023-12-20 16:23:01.000000000 +0100
+++ libcap-ng-0.8.4/bindings/src/capng_swig.i   2024-01-04 12:53:12.131746399 +0100
@@ -30,7 +30,16 @@
 
 %varargs(16, signed capability = 0) capng_updatev;
 
-%except(python) {
+%exception capng_clear {
+  $action
+}
+%exception capng_fill {
+  $action
+}
+%exception capng_setpid {
+  $action
+}
+%exception {
   $action
   if (result < 0) {
     PyErr_SetFromErrno(PyExc_OSError);
``` 
But with the previous swig version the "%except(python)" was simply ignored, so maybe it is safe to remove it at all.

**Comment by stevegrubb** [comment]
I think I'll elect to just delete the exception handler. Less to go deprecated.

**Comment by stevegrubb** [comment]
And a new package pushed into rawhide. I'll go ahead and close this. If anything else comes up, feel free to re-open.

**Comment by dvzrv** [comment]
Hi! :wave: 

I'm packaging this project for Arch Linux.
A new release incorporating the changes in https://github.com/stevegrubb/libcap-ng/commit/d0d4048fe44a96dbce354ef6e588c8dbc21f991a would be much appreciated.
It would allow downstreams not having to backport specific patches :)

**Comment by stevegrubb** [comment]
The 0.8.4 release has this patch in it.

**Comment by dvzrv** [comment]
Argh, my bad, I was meant to point to this commit: https://github.com/stevegrubb/libcap-ng/commit/30453b6553948cd05c438f9f509013e3bb84f25b (the swig issue)

**Comment by stevegrubb** [comment]
This should probably have been a new issue. I'll do a release the week of the 15th, I think there's at least 1 issue to fix before then.

**Comment by stevegrubb** [comment]
new release made.
