### ISSUE TITLE
tarballs downloads from https://people.redhat.com/sgrubb/libcap-ng/ fail due to certificate issues

### ISSUE THREAD

**Issue by kanavin** [stevegrubb/libcap-ng#56]
On my Debian systems, I get the following when trying to fetch the tarball with wget:
```
alex@alex-lx-laptop:~$ wget https://people.redhat.com/sgrubb/libcap-ng/libcap-ng-0.8.5.tar.gz
--2024-08-06 16:49:47--  https://people.redhat.com/sgrubb/libcap-ng/libcap-ng-0.8.5.tar.gz
Resolving people.redhat.com (people.redhat.com)... 209.132.178.26
Connecting to people.redhat.com (people.redhat.com)|209.132.178.26|:443... connected.
ERROR: The certificate of ‘people.redhat.com’ is not trusted.
ERROR: The certificate of ‘people.redhat.com’ doesn't have a known issuer.
```

**Comment by milkylainen** [comment]
Second this. Since the beginning of august, after certificate updates.
I've reported it to the redhat external support line.
It's missing an intermediate certificate, which the server isn't handing out.
The machine in question had the same type of misconfiguration about a year ago.

Rather annoying. This should not happen.

**Comment by kanavin** [comment]
One option is to relocate the tarballs to github. They're not the same as auto-generated github tag archives, but can be manually placed under https://github.com/stevegrubb/libcap-ng/releases

**Comment by stevegrubb** [comment]
True but there's not a lot I can do about it. You can always clone the repo at the release, run ./autogen, ./configure, and then make dist.

**Comment by kanavin** [comment]
But you can relocate the release tarballs to github as suggested perhaps? Also, if you're employed by Red Hat, you can talk to people in charge of people.redhat.com ?

**Comment by stevegrubb** [comment]
Seems to be working now. Closing.
