### ISSUE TITLE
Build Failure for libcap-ng 0.8.5 on SPARC Linux due to Missing Declarations and Errors in cap-ng.c

### ISSUE THREAD

**Issue by kathiv** [stevegrubb/libcap-ng#58]
## Description:

While attempting to build libcap-ng 0.8.5 on a SPARC Linux system, the build fails during the make process. The issue appears to be related to missing declarations, incomplete types, and undefined macros in the cap-ng.c file.

## Environment:

libcap-ng Version: 0.8.5
Target: sparc-unknown-linux-gnu
Compiler: GCC
Configuration Output:
bash
```
libcap-ng Version:      0.8.5
Target:                 sparc-unknown-linux-gnu
Installation prefix:    /usr/local
PYTHON_PREFIX:
Compiler:               gcc
Compiler flags:         -g -O2
```

## Steps to Reproduce:

Download the libcap-ng 0.8.5 source code.
Run the following commands:
bash
Code kopieren
autoreconf -fi
./configure
make
Observe the errors during the build process.

## Observed Behavior## :

The build fails during the compilation of `cap-ng.c` with the following errors and warnings:

- **Undefined macros**:
  - `PR_CAPBSET_READ`
  - `VFS_CAP_REVISION`
  - `VFS_CAP_REVISION_1`
  - `VFS_CAP_REVISION_2`
  - `VFS_CAP_REVISION_MASK`
  - `XATTR_CAPS_SZ_1`
  - `XATTR_CAPS_SZ_2`
  - `VFS_CAP_FLAGS_EFFECTIVE`

- **Incomplete type usage**:
  - `dereferencing pointer to incomplete type`
  - `storage size of 'filedata' isn’t known`

- **Implicit function declarations**:
  - `fgetxattr`
  - `fremovexattr`
  - `fsetxattr`

- **Compilation warnings**:

  - Unused parameters.
  - Labels defined but not used.

- **Specific error excerpt**:
  ```bash
  cap-ng.c:209:15: error: ‘PR_CAPBSET_READ’ undeclared (first use in this function)
  cap-ng.c:316:5: warning: "VFS_CAP_REVISION" is not defined [-Wundef]
  cap-ng.c:630:22: error: storage size of ‘filedata’ isn’t known
  ```

[config.log](https://github.com/user-attachments/files/18128173/config.log)

If you need further details please let me know

**Comment by stevegrubb** [comment]
Reading through the log...this is with gcc 4.6, kernel 2.6.17, and who knows what libc. You'll probably need to backtrack to an older version from the era before those symbols were defined in the header files (and when files were in different places). Release 0.6.5 kind of lines up with the age of your OS. I'd start with that release and then try newer ones until they have a problem again.

The main reason libcap-ng made releases over the years was to support new kernel features and capability definitions. There weren't a lot of bug fixes. So, just get the newest one that works for your OS.

**Comment by kathiv** [comment]
Thanks Release 0.6.5 worked for me
