### ISSUE TITLE
Any plans to make new release?

### ISSUE THREAD

**Issue by kloczek** [stevegrubb/libcap-ng#7]
I think that after+ y it would be good to release new code base :)

**Comment by stevegrubb** [comment]
Yes, there are plans of doing a new release. I was going to add support for the v3 filesystem capabilities first. But maybe I can just do 2 releases. One with current updates and another for the v3 fs updates.

**Comment by kloczek** [comment]
Please do :)

**Comment by stevegrubb** [comment]
0.7.10 was just released. Please find it in the usual places.
