### ISSUE TITLE
undefined reference to `pthread_atfork'

### ISSUE THREAD

**Issue by twoerner** [stevegrubb/libcap-ng#9]
Building on some distros (openSUSE 15.1) requires the addition of -lpthread in order to build successfully:

```
make[2]: Entering directory '/home/trevor/devel/extern/libcap-ng/_build/utils'
/bin/sh ../libtool  --tag=CC   --mode=link gcc -W -Wall -Wshadow -Wformat -Wundef -D_GNU_SOURCE -g -O2   -o pscap pscap.o  -L../src -lcap-ng
libtool: link: gcc -W -Wall -Wshadow -Wformat -Wundef -D_GNU_SOURCE -g -O2 -o .libs/pscap pscap.o  -L../src /home/trevor/devel/extern/libcap-ng/_build/src/.libs/libcap-ng.so
/usr/lib64/gcc/x86_64-suse-linux/8/../../../../x86_64-suse-linux/bin/ld: /home/trevor/devel/extern/libcap-ng/_build/src/.libs/libcap-ng.so: undefined reference to `pthread_atfork'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:488: pscap] Error 1
make[2]: Leaving directory '/home/trevor/devel/extern/libcap-ng/_build/utils'
make[1]: *** [Makefile:448: all-recursive] Error 1
make[1]: Leaving directory '/home/trevor/devel/extern/libcap-ng/_build'
make: *** [Makefile:380: all] Error 2
```

I noticed this with 0.7.10, but the issue also exists on master.

I can build successfully if I do:

```
$ make LDFLAGS="-lpthread"
```

**Comment by stevegrubb** [comment]
The following is copied from a pull request. It probably belongs here for posterity.

I suppose there should be more work on this. Before using pthread_atfork() indiscriminately, I was assured by glibc developers that pthread_atfork has been moved to normal libc. Exactly how they do it I do not directly see. But objdump --syms /usr/lib64/libc-2.30.so | grep atfork shows: __register_atfork and digging into nptl/pthread_atfork.c shows that there is a weak alias that uses __register_atfork.

I have no idea which version of glibc started making pthread_atfork "work" for plain libc linking. Perhaps some work needs to be done to find that and create a proper test for configure that does the right thing for both old and new glibc.

**Comment by stevegrubb** [comment]
Closing this based on merging pull request #10
